/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import javax.swing.JOptionPane;

public class CIFRADOCESAR extends javax.swing.JFrame {

    /**
     * Creates new form CIFRADOCESAR
     */
    public CIFRADOCESAR() {
        initComponents();
        setLocationRelativeTo(null);
        txtResulEncrip.setEditable(false);
        txtMsnDese.setEditable(false);
        JOptionPane.showMessageDialog(null, "INSTRUCCIONES:   "
                + "PARA PODER INGRESAR UN NUEVO MENSAJE YA SEA PARA ENCRIPTAR O DESENCRIPTAR, ES NECESARIO\n"
                + "DAR CLICK EN EL BOTON DE LIMPIAR/BORRAR, PARA PODER ACTIVAR LAS CASILLAS NUEVAMENTE\n"
                + "");
    }

    String cadena = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
    String cadena2 = "abcdefghijklmnñopqrstuvwxyz";
    String cadena3 = "012345678901234567890123456";
    String caracter = "!¡@#$%&/()=¿?+*[]{}-_.:,;óÓ";
    char[] abece = {65, 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
    char[] abece2 = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
    char[] num = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
    char[] car = {'!', '¡', '@', '#', '$', '%', '&', '/', '(', ')', '=', '¿', '?', '+', '*', '[', ']', '{', '}', '-', '_', '.', ':', ',', ';', 'ó', 'Ó'};

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMsn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClaveEnc = new javax.swing.JTextField();
        txtResulEncrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtBorrarencriptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtmsnEncriptado = new javax.swing.JTextField();
        txtClaveDe = new javax.swing.JTextField();
        txtMsnDese = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("INGRESE EL MENSAJE");

        txtMsn.setBackground(new java.awt.Color(153, 153, 153));
        txtMsn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtMsn.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("INGRESE LA CLAVE DE DESPLAZAMIENTO");

        txtClaveEnc.setBackground(new java.awt.Color(153, 153, 153));
        txtClaveEnc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtClaveEnc.setForeground(new java.awt.Color(204, 0, 0));
        txtClaveEnc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveEncKeyTyped(evt);
            }
        });

        txtResulEncrip.setBackground(new java.awt.Color(0, 0, 0));
        txtResulEncrip.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("MENSAJE ENCRIPTADO");

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("EngraversGothic BT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("ENCRIPTACIÓN");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("ENCRIPTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBorrarencriptar.setBackground(new java.awt.Color(0, 102, 0));
        txtBorrarencriptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBorrarencriptar.setText("BORRAR");
        txtBorrarencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrarencriptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMsn, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                                .addComponent(txtResulEncrip)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtClaveEnc, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBorrarencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMsn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBorrarencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtClaveEnc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResulEncrip, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtmsnEncriptado.setBackground(new java.awt.Color(153, 153, 153));
        txtmsnEncriptado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmsnEncriptado.setForeground(new java.awt.Color(0, 0, 0));

        txtClaveDe.setBackground(new java.awt.Color(153, 153, 153));
        txtClaveDe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtClaveDe.setForeground(new java.awt.Color(204, 0, 0));
        txtClaveDe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveDeKeyTyped(evt);
            }
        });

        txtMsnDese.setBackground(new java.awt.Color(0, 0, 0));
        txtMsnDese.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("EngraversGothic BT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("DESENCRIPTACIÓN");

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("DESENCRIPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("INGRESE EL MENSAJE");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("INGRESE LA CLAVE DE DESPLAZAMIENTO");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("MENSAJE DESENCRIPTADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmsnEncriptado)
                                .addComponent(txtMsnDese)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtClaveDe, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addGap(48, 48, 48)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmsnEncriptado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClaveDe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMsnDese, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String mensaje;
        mensaje = txtMsn.getText();
        int clave;
        char[] nuevoMensaje = new char[mensaje.length()];

        if (txtClaveEnc.getText().isEmpty() || txtMsn.getText().isEmpty()) {
            if (txtClaveEnc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "DEBE DE COLOCAR LA CLAVE DE DEZPLAZAMIENTO, RECUERDE, \n"
                        + "\t\t\t SOLO NÚMEROS");
            } else if (txtMsn.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "DEBE DE COLOCAR UN MENSAJE \n"
                        + "");
            }

        } //clave = Integer.parseInt(txtClaveEnc.getText());
        else if (Integer.parseInt(txtClaveEnc.getText()) < 0 || Integer.parseInt(txtClaveEnc.getText()) > 26) {
            JOptionPane.showMessageDialog(this, "LA CLAVE SOLO PUEDE ESTAR ENTRE 0 Y 26");
            txtClaveEnc.setText("");
            txtClaveEnc.setEditable(true);

        } else {
            clave = Integer.parseInt(txtClaveEnc.getText());
            txtClaveEnc.setEditable(false);
            txtMsn.setEditable(false);
            for (int i = 0; i < mensaje.length(); i++) {
                if (mensaje.charAt(i) == ' ') {
                    nuevoMensaje[i] = mensaje.charAt(i);
                } else {
                    for (int j = 0; j < abece.length; j++) {
                        if (mensaje.charAt(i) == cadena.charAt(j)) {

                            if (clave < 0) {
                                nuevoMensaje[i] = abece[(j + clave + abece.length) % abece.length];
                                j = abece.length;
                            } else {
                                nuevoMensaje[i] = abece[(j + clave) % abece.length];
                                j = abece.length;
                            }
                        } else if (mensaje.charAt(i) == cadena2.charAt(j)) {
                            if (clave < 0) {
                                nuevoMensaje[i] = abece2[(j + clave + abece2.length) % abece2.length];
                                j = abece2.length;
                            } else {
                                nuevoMensaje[i] = abece2[(j + clave) % abece2.length];
                                j = abece2.length;
                            }

                        } else if (mensaje.charAt(i) == cadena3.charAt(j)) {
                            if (clave < 0) {
                                nuevoMensaje[i] = num[(j + clave + num.length) % num.length];
                                j = num.length;
                            } else {
                                nuevoMensaje[i] = num[(j + clave) % num.length];
                                j = num.length;
                            }
                        } else if (mensaje.charAt(i) == caracter.charAt(j)) {
                            if (clave < 0) {
                                nuevoMensaje[i] = car[(j + clave + car.length) % car.length];
                                j = car.length;
                            } else {
                                nuevoMensaje[i] = car[(j + clave) % car.length];
                                j = car.length;
                            }
                        } else {
                            nuevoMensaje[i] = mensaje.charAt(i);
                        }
                    }
                }
                // System.out.print(""+nuevoMensaje[i]);
            }
            String s = "";
            System.out.print("EL MENSAJE ENCRIPTADO ES: ---->  ");
            for (int i = 0; i < nuevoMensaje.length; i++) {
                //System.out.print(nuevoMensaje[i]);
                txtResulEncrip.setText(String.valueOf(nuevoMensaje[i]));
                // txtResulEncrip.append();

                s += nuevoMensaje[i];
                System.out.println(s);
            }

            txtResulEncrip.setText(s);
            txtResulEncrip.setForeground(Color.GREEN);
            //  txtResulEncrip.set//setStyle("-fx-text-fill: green; -fx-font-size: 16;"); 
            System.out.println("\n\n\n");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBorrarencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrarencriptarActionPerformed
        txtMsn.setText("");
        txtClaveEnc.setText("");
        txtResulEncrip.setText("");
        txtClaveEnc.setEditable(true);
        txtMsn.setEditable(true);
    }//GEN-LAST:event_txtBorrarencriptarActionPerformed

    private void txtClaveEncKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveEncKeyTyped
        char validar = evt.getKeyChar();
        if (((validar < '0') || (validar > '9')) && (validar != '\b' /*corresponde a BACK_SPACE*/)) {
            getToolkit().beep();
            evt.consume();  // ignorar el evento de teclado
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS, GRACIAS!!!");
        }


    }//GEN-LAST:event_txtClaveEncKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String mensaje;
        mensaje = txtmsnEncriptado.getText();
        int clave;
        char[] nuevoMensaje = new char[mensaje.length()];
        if (txtClaveDe.getText().isEmpty() || txtmsnEncriptado.getText().isEmpty()) {
            if (txtClaveDe.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "DEBE DE COLOCAR LA CLAVE DE DEZPLAZAMIENTO, RECUERDE, \n"
                        + "\t\t\t SOLO NÚMEROS");
            } else if (txtmsnEncriptado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "DEBE DE COLOCAR UN MENSAJE \n"
                        + "");
            } else {
                JOptionPane.showMessageDialog(this, "RELLENE AMBOS CAMPOS DE FAVOR");
            }

        } else if (Integer.parseInt(txtClaveDe.getText()) < 0 || Integer.parseInt(txtClaveDe.getText()) > 26) {
            JOptionPane.showMessageDialog(this, "LA CLAVE SOLO PUEDE ESTAR ENTRE 0 Y 26");
            txtClaveDe.setText("");
            txtClaveDe.setEditable(true);

        } else {
            clave = Integer.parseInt(txtClaveDe.getText());
            txtClaveDe.setEditable(false);
            txtmsnEncriptado.setEditable(false);
            for (int i = 0; i < mensaje.length(); i++) {
                //System.out.println(" aa "+mensaje.charAt(i));
                if (mensaje.charAt(i) == -1) {
                    //System.out.println("Ñ Ñ  Ñ");
                }
                if (mensaje.charAt(i) == ' ') {
                    nuevoMensaje[i] = mensaje.charAt(i);
                } else {
                    for (int j = 0; j < abece.length; j++) {
                        if (mensaje.charAt(i) == abece[j]) {
                            if (j < clave) {
                                nuevoMensaje[i] = abece[(j - clave + abece.length) % abece.length];
                                j = abece.length;
                            } else {
                                nuevoMensaje[i] = abece[(j - clave) % abece.length];
                                j = abece.length;
                            }
                        } else if (mensaje.charAt(i) == abece2[j]) {
                            if (j < clave) {
                                nuevoMensaje[i] = abece2[(j - clave + abece2.length) % abece2.length];
                                j = abece2.length;
                            } else {
                                nuevoMensaje[i] = abece2[(j - clave) % abece2.length];
                                j = abece.length;
                            }
                        } else if (mensaje.charAt(i) == cadena3.charAt(j)) {
                            if (j < clave) {
                                nuevoMensaje[i] = num[(j - clave + num.length) % num.length];
                                j = num.length;
                            } else {
                                nuevoMensaje[i] = num[(j - clave) % num.length];
                                j = num.length;
                            }
                        } else if (mensaje.charAt(i) == caracter.charAt(j)) {
                            if (j < clave) {
                                nuevoMensaje[i] = car[(j - clave + car.length) % car.length];
                                j = car.length;
                            } else {
                                nuevoMensaje[i] = car[(j - clave) % car.length];
                                j = car.length;
                            }
                        } else {
                            nuevoMensaje[i] = mensaje.charAt(i);
                        }
                    }
                }

                //System.out.print("" + nuevoMensaje[i]);
            }
            String s = "";
            System.out.print("EL MENSAJE ENCRIPTADO ES: ---->  ");
            for (int i = 0; i < nuevoMensaje.length; i++) {
                //System.out.print(nuevoMensaje[i]);
                txtMsnDese.setText(String.valueOf(nuevoMensaje[i]));
                // txtResulEncrip.append();

                s += nuevoMensaje[i];
                System.out.println(s);
            }
            txtMsnDese.setForeground(Color.GREEN);
            txtMsnDese.setText(s);
            System.out.println("\n\n\n");

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtClaveDeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveDeKeyTyped

        char validar = evt.getKeyChar();
        if (((validar < '0') || (validar > '9')) && (validar != '\b' /*corresponde a BACK_SPACE*/)) {
            getToolkit().beep();
            evt.consume();  // ignorar el evento de teclado
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS, GRACIAS!!!");
        }


    }//GEN-LAST:event_txtClaveDeKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtmsnEncriptado.setText("");
        txtClaveDe.setText("");
        txtMsnDese.setText("");
        txtClaveDe.setEditable(true);
        txtmsnEncriptado.setEditable(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CIFRADOCESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CIFRADOCESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CIFRADOCESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CIFRADOCESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CIFRADOCESAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton txtBorrarencriptar;
    private javax.swing.JTextField txtClaveDe;
    private javax.swing.JTextField txtClaveEnc;
    private javax.swing.JTextField txtMsn;
    private javax.swing.JTextField txtMsnDese;
    private javax.swing.JTextField txtResulEncrip;
    private javax.swing.JTextField txtmsnEncriptado;
    // End of variables declaration//GEN-END:variables
}
